return {
	lazy = false,
	"catppuccin/nvim",
	name = "catppuccin",
	main = "catppuccin",
	priority = 1000,
	opts = {
		flavour = "frappe",
		background = {
			light = "latte",
			dark = "frappe",
		},
		transparent_background = false,
		show_end_of_buffer = false,
		term_colors = false,
		dim_inactive = {
			enabled = true,
			shade = "dark",
			percentage = 0.15,
		},
		no_italic = false,
		no_bold = false,
		no_underline = false,
		styles = {
			comments = { "italic" },
			conditionals = { "bold" },
			loops = { "bold" },
			functions = {},
			keywords = { "bold" },
			strings = {},
			variables = { "underline" },
			numbers = {},
			booleans = {},
			properties = { "underline" },
			types = { "italic" },
			operators = {},
			-- miscs = {}, -- Uncomment to turn off hard-coded styles
		},
		color_overrides = {},
		custom_highlights = {},
		default_integrations = true,
		integrations = {
			cmp = true,
			nvimtree = true,
			treesitter = true,
			notify = true,
			flash = true,
			fzf = true,
			gitsigns = true,
			harpoon = true,
			hop = true,
			leap = true,
			lsp_saga = true,
			markdown = true,
			neotree = true,
			neogit = true,
			neotest = true,
			notifier = true,
			cmp = true,
			dap = true,
			dap_ui = true,
			native_lsp = {
				enabled = true,
				virtual_text = {
					errors = { "bold" },
					hints = {},
					warnings = { "bold" },
					information = { "italic" },
					ok = {},
				},
				underlines = {
					errors = { "underline" },
					hints = { "underline" },
					warnings = { "underline" },
					information = { "underline" },
					ok = { "underline" },
				},
				inlay_hints = {
					background = true,
				},
			},
			notify = true,
			nvim_surround = true,
			treesitter_context = true,
			treesitter = true,
			nvimtree = true,
			rainbow_delimiters = true,
			render_markdown = true,
			telescope = {
				enabled = true,
				-- style = "nvchad"
			},
			dadbod_ui = true,
			which_key = true,
			mini = {
				enabled = true,
				indentscope_color = "",
			},
		},
	},
	config = function()
		vim.cmd.colorscheme("catppuccin-frappe")
	end,
}
