return {
	{
		event = "VeryLazy",
		main = "nvim-treesitter.configs",
		"nvim-treesitter/nvim-treesitter",
		dependencies = { "nvim-treesitter/nvim-treesitter-refactor" },
		build = ":TSUpdate",
		opts = {
			ensure_installed = {
				"asm",
				"bash",
				"c",
				"cmake",
				"comment",
				"commonlisp",
				"cpp",
				"diff",
				"disassembly",
				"dockerfile",
				"editorconfig",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"goctl",
				"gomod",
				"gosum",
				"gotmpl",
				"gowork",
				"jsonc",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"markdown_inline",
				"nasm",
				"python",
				"rust",
				"tmux",
				"toml",
				"yaml",
				"zig",
			},
			sync_install = false,
			auto_install = true,
			ignore_install = {},
			highlight = {
				enable = true,
				disable = {},
				additional_vim_regex_highlighting = false,
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "gnn", -- set to `false` to disable one of the mappings
					node_incremental = "grn",
					scope_incremental = "grc",
					node_decremental = "grm",
				},
			},
			indent = {
				enable = true,
			},
			refactor = {
				highlight_current_scope = { enable = true },
				smart_rename = {
					enable = false,
					keymaps = {
						smart_rename = "grr",
					},
				},
				highlight_definitions = {
					enable = true,
					clear_on_cursor_move = true,
				},
				navigation = {
					enable = false,
					keymaps = {
						goto_definition_lsp_fallback = false, -- "gnd",
						list_definitions = "gnD",
						list_definitions_toc = "gO",
						goto_next_usage = "<a-*>",
						goto_previous_usage = "<a-#>",
					},
				},
			},
		},
	},
	{
		event = "VeryLazy",
		main = "treesitter-context",
		"nvim-treesitter/nvim-treesitter-context",
		opts = {
			enable = true,
			max_lines = 5,
			min_window_height = 0,
			line_numbers = true,
			multiline_threshold = 10,
			trim_scope = "inner",
			mode = "cursor", --"cursor", --"toplnie",
			separator = nil,
			zindex = 20,
			on_attach = function(bufnr)
				return true
			end,
		},
	},
}
